# Documentation of data beyond the main trials codebook, created in a separate script.
#
# Documentation added here on a as needed basis.
#
# Outputs:
# Data dictionary: similar to the trials codebook, includes information on data elements in specific tables
# Table definitions: includes overview information on tables included in data dictionary

library(dplyr)



# Prepare "table definitions" ---------------------------------------------

tables <- tibble::tibble(
  table = character(),
  description = character(),
  location = character()
)

add_table <- function(tables, filepath, description) {

  filepath <- fs::path_ext_remove(filepath)

  tables |>
    tibble::add_row(
      table = fs::path_file(filepath),
      location = fs::path_rel(filepath),
      description = description
    )

}


# Prepare "data dictionary" -----------------------------------------------

dictionary <- tibble::tibble(
  table = character(),
  column = character(),
  type = character(),
  description = character()
)

create_dictionary <- function(filepath) {

  df <- readr::read_rds(filepath)

    tibble::tibble(
      table = fs::path_file(filepath) |> fs::path_ext_remove(),
      column = colnames(df),
      type = df |> purrr::map_chr(class) |> tolower()
    )

}

add_dictionary <- function(dictionary, new_dictionary, new_descriptions) {

    dictionary |>
      tibble::add_row(
        left_join(new_dictionary, new_descriptions, by = "column")
      )

  }

# add_dictionary <- function(dictionary, filepath) {
#
#     df <- readr::read_rds(filepath)
#
#     new_dictionary <-
#       tibble::tibble(
#         table = fs::path_file(filepath) |> fs::path_ext_remove(),
#         column = colnames(df),
#         type = df |> purrr::map_chr(class) |> tolower()
#       )
#
#     dictionary |>
#       tibble::add_row(new_dictionary)
#
#   }


# Create documentation ----------------------------------------------------

## 1. Tables to add -------------------------------------------------------
path_trials <- here::here("data", "processed", "trials.rds")

path_reg_cr <- here::here("data", "processed", "registries", "registry-crossreg.rds")

path_trn_cr <- here::here("data", "processed", "trn", "cross-registrations.rds")


## 2. Add to "tables definitions" -----------------------------------------

tables <-
  tables |>

  add_table(path_trials,
  "Main table building on IntoValue 1 and 2. Documentation of variables in separate 'codebook'"
  ) |>

  add_table(path_reg_cr,
  "Generated by 'combine-ctgov-drks-trials.R'. Captures cross-registrations (`crossreg_trn` column) mentioned in registration in `id` column. `id` column includes trns found in 'trials' table `id` column, as well as additional trns found in metadata, abstract, or full-text of an associated publication. These additional `id`s are not included as `id`s but do appear as `crossreg_trn` in 'cross-registrations' table."
  ) |>

  add_table(path_trn_cr,
  "Generated by 'prepare-cross-registrations.R'. Captures cross-registrations (`crossreg_trn` column) associated with `id` in 'trials' table `id` column, as well as the source(s) of the cross-registration. The `id` column is limited to `id`s in 'trials' table `id` column; some `id`s in 'registry-crossreg' are therefore missing from the `id` column but are included in the `crossreg_trn` column."
  )


## 3. Add to "data dictionary" --------------------------------------------

# Create descriptions
dictionary_reg_cr <- create_dictionary(path_reg_cr)
descriptions_reg_cr <- tibble::tribble(
  ~column, ~description,
  "id", "Trial registration number, either a ClinicalTrials.gov NCT id or DRKS id. Includes trns found in 'trials' table `id` column, as well as additional trns found in metadata, abstract, or full-text of an associated publication.",
  "crossreg_registry", "Registry of `crossreg_trn`",
  "crossreg_trn", "Trial registration number that appears in `id` registration"

)

dictionary_trn_cr <- create_dictionary(path_trn_cr)
descriptions_trn_cr <- tibble::tribble(
  ~column, ~description,
  "id", "Trial registration number, either a ClinicalTrials.gov NCT id or DRKS id. Subset of `id` in 'trials' table.",
  "pmid", "Publication PMID",
  "doi", "Publication DOI",
  "crossreg_trn", "Trial registration number found in one or more sources encoded with `is_crossreg_`",
  "crossreg_registry", "Registry of `crossreg_trn`",
  "is_crossreg_secondary_id", "Whether `crossreg_trn` appears in PubMed secondary id of results publication",
  "is_crossreg_abstract", "Whether `crossreg_trn` appears in PubMed abstract of results publication",
  "is_crossreg_ft", "Whether `crossreg_trn` appears in full text of results publication",
  "is_crossreg_reg", "Whether `crossreg_trn` appears in `id` registration. Taken from 'registry-crossreg' table."
)

# Add
dictionary <-
  dictionary |>
  add_dictionary(dictionary_reg_cr, descriptions_reg_cr) |>
  add_dictionary(dictionary_trn_cr, descriptions_trn_cr)


# Save documentation ------------------------------------------------------

readr::write_csv(tables, here::here("data", "processed", "tables-definitions.csv"))
readr::write_csv(dictionary, here::here("data", "processed", "data-dictionary.csv"))
